metadata:
  camera_intrinsics:
    - alias: alphasense_front_center_caminfo
      file: "*_alphasense.bag"
      topic: "/boxi/alphasense/front_center/camera_info"

  frame_transforms:
    - frame_id: alphasense_front_center
      file: "*_tf_minimal.bag"
      topic: /tf_static
      reference_frame_id: box_base

data:
  image_topics:
    - alias: alphasense_front_center
      file: "*_alphasense.bag"
      topic: "/boxi/alphasense/front_center/image_raw/compressed"
      format: jpeg
      compressed: true
      camera_intrinsics: alphasense_front_center_caminfo
      description: "10Hz - 1440x1080 - Sevensense Alphasense/CoreResearch front center (Sony IMX-273, Color, 1.6MP)"
  