# .pre-commit-config.yaml
# From https://sbarnea.com/lint/black/
---
repos:
  - repo: https://github.com/python/black.git
    rev: 24.4.0
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=120]
        require_serial: true
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=120, "--ignore=E402,E501,W503,C901,E731,W605,E722", "--extend-ignore=E203", "--exclude=_*,.vscode,.git", "--exclude=*_pb2*"]
        language_version: python3
        require_serial: true
  - repo: local
    hooks:
      - id: jupyter-nb-clear-output
        name: jupyter-nb-clear-output
        files: \.ipynb$
        stages: [commit]
        language: system
        entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0 # Use the version you want
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=5000"]

