# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recording_status.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode("latin1"))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="recording_status.proto",
    package="recording_status",
    syntax="proto3",
    serialized_pb=_b(
        '\n\x16recording_status.proto\x12\x10recording_status",\n\x16RecordingStatusRequest\x12\x12\n\ndebug_info\x18\x01 \x01(\t"1\n\x17RecordingStatusResponse\x12\x16\n\x0estop_recording\x18\x01 \x01(\x08\x32w\n\x0fRecordingStatus\x12\x64\n\x0bSendMessage\x12(.recording_status.RecordingStatusRequest\x1a).recording_status.RecordingStatusResponse"\x00\x62\x06proto3'
    ),
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


_RECORDINGSTATUSREQUEST = _descriptor.Descriptor(
    name="RecordingStatusRequest",
    full_name="recording_status.RecordingStatusRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="debug_info",
            full_name="recording_status.RecordingStatusRequest.debug_info",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=44,
    serialized_end=88,
)


_RECORDINGSTATUSRESPONSE = _descriptor.Descriptor(
    name="RecordingStatusResponse",
    full_name="recording_status.RecordingStatusResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="stop_recording",
            full_name="recording_status.RecordingStatusResponse.stop_recording",
            index=0,
            number=1,
            type=8,
            cpp_type=7,
            label=1,
            has_default_value=False,
            default_value=False,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=90,
    serialized_end=139,
)

DESCRIPTOR.message_types_by_name["RecordingStatusRequest"] = _RECORDINGSTATUSREQUEST
DESCRIPTOR.message_types_by_name["RecordingStatusResponse"] = _RECORDINGSTATUSRESPONSE

RecordingStatusRequest = _reflection.GeneratedProtocolMessageType(
    "RecordingStatusRequest",
    (_message.Message,),
    dict(
        DESCRIPTOR=_RECORDINGSTATUSREQUEST,
        __module__="recording_status_pb2",
        # @@protoc_insertion_point(class_scope:recording_status.RecordingStatusRequest)
    ),
)
_sym_db.RegisterMessage(RecordingStatusRequest)

RecordingStatusResponse = _reflection.GeneratedProtocolMessageType(
    "RecordingStatusResponse",
    (_message.Message,),
    dict(
        DESCRIPTOR=_RECORDINGSTATUSRESPONSE,
        __module__="recording_status_pb2",
        # @@protoc_insertion_point(class_scope:recording_status.RecordingStatusResponse)
    ),
)
_sym_db.RegisterMessage(RecordingStatusResponse)


try:
    # THESE ELEMENTS WILL BE DEPRECATED.
    # Please use the generated *_pb2_grpc.py files instead.
    import grpc
    from grpc.framework.common import cardinality
    from grpc.framework.interfaces.face import utilities as face_utilities
    from grpc.beta import implementations as beta_implementations
    from grpc.beta import interfaces as beta_interfaces

    class RecordingStatusStub(object):

        def __init__(self, channel):
            """Constructor.

            Args:
              channel: A grpc.Channel.
            """
            self.SendMessage = channel.unary_unary(
                "/recording_status.RecordingStatus/SendMessage",
                request_serializer=RecordingStatusRequest.SerializeToString,
                response_deserializer=RecordingStatusResponse.FromString,
            )

    class RecordingStatusServicer(object):

        def SendMessage(self, request, context):
            context.set_code(grpc.StatusCode.UNIMPLEMENTED)
            context.set_details("Method not implemented!")
            raise NotImplementedError("Method not implemented!")

    def add_RecordingStatusServicer_to_server(servicer, server):
        rpc_method_handlers = {
            "SendMessage": grpc.unary_unary_rpc_method_handler(
                servicer.SendMessage,
                request_deserializer=RecordingStatusRequest.FromString,
                response_serializer=RecordingStatusResponse.SerializeToString,
            ),
        }
        generic_handler = grpc.method_handlers_generic_handler("recording_status.RecordingStatus", rpc_method_handlers)
        server.add_generic_rpc_handlers((generic_handler,))

    class BetaRecordingStatusServicer(object):
        """The Beta API is deprecated for 0.15.0 and later.

        It is recommended to use the GA API (classes and functions in this
        file not marked beta) for all further purposes. This class was generated
        only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""

        def SendMessage(self, request, context):
            context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)

    class BetaRecordingStatusStub(object):
        """The Beta API is deprecated for 0.15.0 and later.

        It is recommended to use the GA API (classes and functions in this
        file not marked beta) for all further purposes. This class was generated
        only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""

        def SendMessage(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
            raise NotImplementedError()

        SendMessage.future = None

    def beta_create_RecordingStatus_server(
        servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None
    ):
        """The Beta API is deprecated for 0.15.0 and later.

        It is recommended to use the GA API (classes and functions in this
        file not marked beta) for all further purposes. This function was
        generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
        request_deserializers = {
            ("recording_status.RecordingStatus", "SendMessage"): RecordingStatusRequest.FromString,
        }
        response_serializers = {
            ("recording_status.RecordingStatus", "SendMessage"): RecordingStatusResponse.SerializeToString,
        }
        method_implementations = {
            ("recording_status.RecordingStatus", "SendMessage"): face_utilities.unary_unary_inline(
                servicer.SendMessage
            ),
        }
        server_options = beta_implementations.server_options(
            request_deserializers=request_deserializers,
            response_serializers=response_serializers,
            thread_pool=pool,
            thread_pool_size=pool_size,
            default_timeout=default_timeout,
            maximum_timeout=maximum_timeout,
        )
        return beta_implementations.server(method_implementations, options=server_options)

    def beta_create_RecordingStatus_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
        """The Beta API is deprecated for 0.15.0 and later.

        It is recommended to use the GA API (classes and functions in this
        file not marked beta) for all further purposes. This function was
        generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
        request_serializers = {
            ("recording_status.RecordingStatus", "SendMessage"): RecordingStatusRequest.SerializeToString,
        }
        response_deserializers = {
            ("recording_status.RecordingStatus", "SendMessage"): RecordingStatusResponse.FromString,
        }
        cardinalities = {
            "SendMessage": cardinality.Cardinality.UNARY_UNARY,
        }
        stub_options = beta_implementations.stub_options(
            host=host,
            metadata_transformer=metadata_transformer,
            request_serializers=request_serializers,
            response_deserializers=response_deserializers,
            thread_pool=pool,
            thread_pool_size=pool_size,
        )
        return beta_implementations.dynamic_stub(
            channel, "recording_status.RecordingStatus", cardinalities, options=stub_options
        )

except ImportError:
    pass
# @@protoc_insertion_point(module_scope)
