# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stop_recording.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode("latin1"))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="stop_recording.proto",
    package="stop_recording",
    syntax="proto3",
    serialized_pb=_b(
        '\n\x14stop_recording.proto\x12\x0estop_recording"*\n\x14StopRecordingRequest\x12\x12\n\ndebug_info\x18\x01 \x01(\t")\n\x15StopRecordingResponse\x12\x10\n\x08response\x18\x01 \x01(\t2m\n\rStopRecording\x12\\\n\x0bSendMessage\x12$.stop_recording.StopRecordingRequest\x1a%.stop_recording.StopRecordingResponse"\x00\x62\x06proto3'
    ),
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


_STOPRECORDINGREQUEST = _descriptor.Descriptor(
    name="StopRecordingRequest",
    full_name="stop_recording.StopRecordingRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="debug_info",
            full_name="stop_recording.StopRecordingRequest.debug_info",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=40,
    serialized_end=82,
)


_STOPRECORDINGRESPONSE = _descriptor.Descriptor(
    name="StopRecordingResponse",
    full_name="stop_recording.StopRecordingResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="response",
            full_name="stop_recording.StopRecordingResponse.response",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=_b("").decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            options=None,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=84,
    serialized_end=125,
)

DESCRIPTOR.message_types_by_name["StopRecordingRequest"] = _STOPRECORDINGREQUEST
DESCRIPTOR.message_types_by_name["StopRecordingResponse"] = _STOPRECORDINGRESPONSE

StopRecordingRequest = _reflection.GeneratedProtocolMessageType(
    "StopRecordingRequest",
    (_message.Message,),
    dict(
        DESCRIPTOR=_STOPRECORDINGREQUEST,
        __module__="stop_recording_pb2",
        # @@protoc_insertion_point(class_scope:stop_recording.StopRecordingRequest)
    ),
)
_sym_db.RegisterMessage(StopRecordingRequest)

StopRecordingResponse = _reflection.GeneratedProtocolMessageType(
    "StopRecordingResponse",
    (_message.Message,),
    dict(
        DESCRIPTOR=_STOPRECORDINGRESPONSE,
        __module__="stop_recording_pb2",
        # @@protoc_insertion_point(class_scope:stop_recording.StopRecordingResponse)
    ),
)
_sym_db.RegisterMessage(StopRecordingResponse)


try:
    # THESE ELEMENTS WILL BE DEPRECATED.
    # Please use the generated *_pb2_grpc.py files instead.
    import grpc
    from grpc.framework.common import cardinality
    from grpc.framework.interfaces.face import utilities as face_utilities
    from grpc.beta import implementations as beta_implementations
    from grpc.beta import interfaces as beta_interfaces

    class StopRecordingStub(object):

        def __init__(self, channel):
            """Constructor.

            Args:
              channel: A grpc.Channel.
            """
            self.SendMessage = channel.unary_unary(
                "/stop_recording.StopRecording/SendMessage",
                request_serializer=StopRecordingRequest.SerializeToString,
                response_deserializer=StopRecordingResponse.FromString,
            )

    class StopRecordingServicer(object):

        def SendMessage(self, request, context):
            context.set_code(grpc.StatusCode.UNIMPLEMENTED)
            context.set_details("Method not implemented!")
            raise NotImplementedError("Method not implemented!")

    def add_StopRecordingServicer_to_server(servicer, server):
        rpc_method_handlers = {
            "SendMessage": grpc.unary_unary_rpc_method_handler(
                servicer.SendMessage,
                request_deserializer=StopRecordingRequest.FromString,
                response_serializer=StopRecordingResponse.SerializeToString,
            ),
        }
        generic_handler = grpc.method_handlers_generic_handler("stop_recording.StopRecording", rpc_method_handlers)
        server.add_generic_rpc_handlers((generic_handler,))

    class BetaStopRecordingServicer(object):
        """The Beta API is deprecated for 0.15.0 and later.

        It is recommended to use the GA API (classes and functions in this
        file not marked beta) for all further purposes. This class was generated
        only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""

        def SendMessage(self, request, context):
            context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)

    class BetaStopRecordingStub(object):
        """The Beta API is deprecated for 0.15.0 and later.

        It is recommended to use the GA API (classes and functions in this
        file not marked beta) for all further purposes. This class was generated
        only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""

        def SendMessage(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
            raise NotImplementedError()

        SendMessage.future = None

    def beta_create_StopRecording_server(
        servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None
    ):
        """The Beta API is deprecated for 0.15.0 and later.

        It is recommended to use the GA API (classes and functions in this
        file not marked beta) for all further purposes. This function was
        generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
        request_deserializers = {
            ("stop_recording.StopRecording", "SendMessage"): StopRecordingRequest.FromString,
        }
        response_serializers = {
            ("stop_recording.StopRecording", "SendMessage"): StopRecordingResponse.SerializeToString,
        }
        method_implementations = {
            ("stop_recording.StopRecording", "SendMessage"): face_utilities.unary_unary_inline(servicer.SendMessage),
        }
        server_options = beta_implementations.server_options(
            request_deserializers=request_deserializers,
            response_serializers=response_serializers,
            thread_pool=pool,
            thread_pool_size=pool_size,
            default_timeout=default_timeout,
            maximum_timeout=maximum_timeout,
        )
        return beta_implementations.server(method_implementations, options=server_options)

    def beta_create_StopRecording_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
        """The Beta API is deprecated for 0.15.0 and later.

        It is recommended to use the GA API (classes and functions in this
        file not marked beta) for all further purposes. This function was
        generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
        request_serializers = {
            ("stop_recording.StopRecording", "SendMessage"): StopRecordingRequest.SerializeToString,
        }
        response_deserializers = {
            ("stop_recording.StopRecording", "SendMessage"): StopRecordingResponse.FromString,
        }
        cardinalities = {
            "SendMessage": cardinality.Cardinality.UNARY_UNARY,
        }
        stub_options = beta_implementations.stub_options(
            host=host,
            metadata_transformer=metadata_transformer,
            request_serializers=request_serializers,
            response_deserializers=response_deserializers,
            thread_pool=pool,
            thread_pool_size=pool_size,
        )
        return beta_implementations.dynamic_stub(
            channel, "stop_recording.StopRecording", cardinalities, options=stub_options
        )

except ImportError:
    pass
# @@protoc_insertion_point(module_scope)
