#!/usr/bin/env python

import sys

from rqt_recording_plugin.recording_plugin import RecordingPlugin
from rqt_gui.main import Main

plugin = 'rqt_recording'
main = Main()
sys.exit(main.main(standalone=plugin))
