plugin_config_file: '$(rospack find bringup_elevation_mapping)/config/grand_tour_plugin_config.yaml'

pointcloud_channel_fusions:
  rgb: 'color'
  default: 'average'

image_channel_fusions:
  rgb: 'color'
  default: 'exponential'
  feat_.*: 'exponential'
  sem_.*: 'exponential'

#### Publishers ########
# topic_name:
#   layers:               # Choose from 'elevation', 'variance', 'traversability', 'time', 'normal_x', 'normal_y', 'normal_z', 'color', plugin_layer_names
#   basic_layers:         # basic_layers for valid cell computation (e.g. Rviz): Choose a subset of `layers`.
#   fps:                  # Publish rate. Use smaller value than `map_acquire_fps`.

publishers:
  elevation_map_raw:
    layers: ['elevation', 'traversability', 'variance', 'rgb', 'upper_bound', 'inpaint', 'smooth', 'min_filter']
    basic_layers: ['elevation', 'traversability']
    fps: 5.0

  # elevation_map_recordable:
  #   layers: ['elevation', 'traversability', 'variance', 'rgb']
  #   basic_layers: ['elevation', 'traversability']
  #   fps: 2.0

  # filtered_elevation_map:
  #   layers: ['inpaint', 'smooth', 'min_filter', 'upper_bound']
  #   basic_layers: ['inpaint']
  #   fps: 5.0

#### Subscribers ########  NEVER ADD EMPTY LINE HERE OTHERWISE CPP WILL FAIL!!
subscribers:
  hesai:
    topic_name: /dlio/deskewed_point_cloud
    data_type: pointcloud
  livox:
    topic_name: /gt_box/livox/lidar_filtered
    data_type: pointcloud
  hdr_front:
    topic_name: /gt_box/hdr_front_rect/image_rect/compressed
    camera_info_topic_name: /gt_box/hdr_front_rect/camera_info
    data_type: image
  hdr_left:
    topic_name: /gt_box/hdr_left_rect/image_rect/compressed
    camera_info_topic_name: /gt_box/hdr_left_rect/camera_info
    data_type: image
  hdr_right:
    topic_name: /gt_box/hdr_right_rect/image_rect/compressed
    camera_info_topic_name: /gt_box/hdr_right_rect/camera_info
    data_type: image
