plugin_config_file: '$(rospack find bringup_elevation_mapping)/config/grand_tour_plugin_config.yaml'

pointcloud_channel_fusions:
  rgb: 'color'
  default: 'average'

image_channel_fusions:
  rgb: 'color'
  default: 'exponential'
  feat_.*: 'exponential'
  sem_.*: 'exponential'

#### Publishers ########
# topic_name:
#   layers:               # Choose from 'elevation', 'variance', 'traversability', 'time', 'normal_x', 'normal_y', 'normal_z', 'color', plugin_layer_names
#   basic_layers:         # basic_layers for valid cell computation (e.g. Rviz): Choose a subset of `layers`.
#   fps:                  # Publish rate. Use smaller value than `map_acquire_fps`.

publishers:
  elevation_map_raw:
    layers: ['elevation', 'traversability', 'variance', 'rgb', 'upper_bound']
    basic_layers: ['elevation', 'traversability']
    fps: 5.0

  elevation_map_recordable:
    layers: ['elevation', 'traversability', 'variance', 'rgb']
    basic_layers: ['elevation', 'traversability']
    fps: 2.0

  filtered_elevation_map:
    layers: ['inpaint', 'smooth', 'min_filter', 'upper_bound']
    basic_layers: ['inpaint']
    fps: 5.0

#### Subscribers ########
subscribers:
  heasi:
    topic_name: /gt_box/hesai/points
    data_type: pointcloud

  livox:
    topic_name: /gt_box/livox/lidar
    data_type: pointcloud