general:
  world_frame: "enu_origin"
  logging_level: debug
  allow_reset_map_service: true

map:
  type: hashed_chunked_wavelet_octree
  min_cell_width: { meters: 0.2 }

map_operations:
  - type: threshold_map
    once_every: { seconds: 2.0 }
  - type: prune_map
    once_every: { seconds: 10.0 }
  - type: publish_map
    once_every: { seconds: 2.0 }

measurement_integrators:
  hesai_xt32:
    projection_model:
      type: spherical_projector
      lidar_origin_to_beam_origin: { millimeters: 0.0 }
      lidar_origin_to_sensor_origin_z_offset: { millimeters: 0.0 }
      elevation:
        num_cells: 32
        min_angle: { degrees: -16.0 }
        max_angle: { degrees: 15.0 }
      azimuth:
        num_cells: 1024
        min_angle: { degrees: -180.0 }
        max_angle: { degrees: 180.0 }
    measurement_model:
      type: continuous_beam
      angle_sigma: { degrees: 0.035 }
      # NOTE: For best results, we recommend setting range_sigma to
      #       max(min_cell_width / 2, ouster_noise) where ouster_noise = 0.05
      range_sigma: { meters: 0.05 }
      scaling_free: 0.2
      scaling_occupied: 0.4
    integration_method:
      type: hashed_chunked_wavelet_integrator
      min_range: { meters: 1.0 }
      max_range: { meters: 75.0 }

inputs:
  - type: pointcloud_topic
    topic_name: /gt_box/hesai/points_last
    topic_type: PointCloud2
    measurement_integrator_names: hesai_xt32
    undistort_motion: false
    topic_queue_length: 10
    max_wait_for_pose: { seconds: 1.0 }
    # reprojected_pointcloud_topic_name: "/wavemap/reprojected_pointcloud"
    # projected_range_image_topic_name: "/wavemap/projected_range_image"