x-common-config: &common-config
  build:
    context: "$HOME/git/grand_tour_box/box_utils/box_auto/docker"
    dockerfile: "$HOME/git/grand_tour_box/box_utils/box_auto/docker/box.Dockerfile"
    ssh:
      default: "$HOME/.ssh/id_rsa_2"
  image: rslethz/grand_tour_box
  runtime: nvidia
  # network_mode: host
  privileged: true
  environment:
    QT_X11_NO_MITSHM: "1"
    XAUTHORITY: "/root/.docker.xauth"
    DISPLAY: "$DISPLAY"  
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities:
              - gpu
              - utility # nvidia-smi
              - compute # CUDA
              - video   # encoding 
  volumes:
    - /Data/Projects/GrandTour/deployment_day_1/2024-10-01-11-29-55:/mission_data
    - /home/jonfrey/git/grand_tour_box:/home/catkin_ws/src/grand_tour_box
x-ros2-common-config: &ros2-common-config
  build:
    context: "$HOME/git/grand_tour_box/box_utils/box_auto/docker"
    dockerfile: "$HOME/git/grand_tour_box/box_utils/box_auto/docker/box_ros2.Dockerfile"
    ssh:
      default: "$HOME/.ssh/id_rsa_2"
  image: rslethz/grand_tour_box_ros2
  runtime: nvidia
  # network_mode: host
  privileged: true
  environment:
    QT_X11_NO_MITSHM: "1"
    XAUTHORITY: "/root/.docker.xauth"
    DISPLAY: "$DISPLAY"  
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: all
            capabilities:
              - gpu
              - utility # nvidia-smi
              - compute # CUDA
              - video   # encoding 
  volumes:
    - /Data/Projects/GrandTour/deployment_day_1/2024-10-01-11-47-44:/mission_data
    - /home/jonfrey/git/grand_tour_box:/home/catkin_ws/src/grand_tour_box # For debugging


services:

  export_raw_imu_bag:
    <<: *common-config
    container_name: export_raw_imu_bag
    command: ["python3", "/home/catkin_ws/src/grand_tour_box/box_utils/box_auto/scripts/export_raw_imu_bag.py"]

  export_gps_gt_trajectory_bag:
    <<: *common-config
    container_name: export_gps_gt_trajectory_bag
    command: ["python3", "/home/catkin_ws/src/grand_tour_box/box_utils/box_auto/scripts/export_gps_gt_trajectory_bag.py"]


  mcap_to_rosbag:
    <<: *common-config
    container_name: mcap_to_rosbag
    command: ["python3", "/home/catkin_ws/src/grand_tour_box/box_utils/box_auto/scripts/mcap_to_rosbag.py"]
    # depends_on:
    #   ros2_fix_bags:
    #     condition: service_completed_successfully

  zed2i:
    <<: *common-config
    container_name: zed2i
    command: ["python3", "/home/catkin_ws/src/grand_tour_box/box_utils/box_auto/scripts/zed2i.py"]

  merge_mission:
    <<: *common-config
    container_name: merge_mission
    command: ["python3", "/home/catkin_ws/src/grand_tour_box/box_utils/box_auto/scripts/merge_mission.py"]
    depends_on:
      mcap_to_rosbag:
        condition: service_completed_successfully
      zed2i:
        condition: service_completed_successfully

  create_tf_static:
    <<: *common-config
    container_name: create_tf_static
    command: ["python3", "/home/catkin_ws/src/grand_tour_box/box_utils/box_auto/scripts/create_tf_static.py"]
    depends_on:
      merge_mission:
        condition: service_completed_successfully

  ap20_python_online_matcher:
    <<: *common-config
    container_name: ap20_python_online_matcher
    command: ["python3", "/home/catkin_ws/src/grand_tour_box/box_utils/box_auto/scripts/ap20_python_online_matcher.py"]
    depends_on:
      merge_mission:
        condition: service_completed_successfully

  hesai:
    <<: *common-config
    container_name: hesai
    command: ["python3", "/home/catkin_ws/src/grand_tour_box/box_utils/box_auto/scripts/hesai.py"]
    # depends_on:
    #   merge_mission:
    #     condition: service_completed_successfully

  cpt7:
    <<: *common-config
    container_name: cpt7
    command: ["python3", "/home/catkin_ws/src/grand_tour_box/box_utils/box_auto/scripts/cpt7.py"]
    depends_on:
      merge_mission:
        condition: service_completed_successfully
  
  imu_timesync:
    <<: *common-config
    container_name: imu_timesync
    command: ["python3", "/home/catkin_ws/src/grand_tour_box/box_utils/box_auto/scripts/imu_timesync.py"]
    depends_on:
      cpt7:
        condition: service_completed_successfully
      create_tf_static:
        condition: service_completed_successfully

  topic_freq:
    <<: *common-config
    container_name: topic_freq
    command: ["python3", "/home/catkin_ws/src/grand_tour_box/box_utils/box_auto/scripts/topic_freq.py"]
    depends_on:
      hesai:
        condition: service_completed_successfully
      cpt7:
        condition: service_completed_successfully
      ap20_python_online_matcher:
        condition: service_completed_successfully
  
  color_correction:
    <<: *common-config
    container_name: color_correction
    command: ["python3", "/home/catkin_ws/src/grand_tour_box/box_utils/box_auto/scripts/color_correction.py"]
    # depends_on:
    #   update_camera_info:
    #     condition: service_completed_successfully

  # Optionals
  # update_camera_info:
  #   <<: *common-config
  #   container_name: update_camera_info
  #   command: ["python3", "/home/catkin_ws/src/grand_tour_box/box_utils/box_auto/scripts/update_camera_info.py"]
  #   depends_on:
  #     merge_mission:
  #       condition: service_completed_successfully

  # rectify:
  #   <<: *common-config
  #   container_name: rectify
  #   command: ["python3", "/home/catkin_ws/src/grand_tour_box/box_utils/box_auto/scripts/rectify.py"]
  #   depends_on:
  #     update_camera_info:
  #       condition: service_completed_successfully

  # # ros2_fix_bags:
  # #   <<: *ros2-common-config
  # #   container_name: fix_mcaps
  # #   command: ["python3", "/home/catkin_ws/src/grand_tour_box/box_utils/box_auto/scripts/repair_ros2.py"]
  # # repair_bags:
  # #   <<: *common-config
  # #   container_name: repair_bags
  # #   command: ["python3", "/home/catkin_ws/src/grand_tour_box/box_utils/box_auto/scripts/repair_bags.py"]
