/gt_box/alphasense_driver_node/cam1/color/image: cam1_sensor_frame_helper
/gt_box/alphasense_driver_node/cam2/color/image: cam2_sensor_frame_helper
/gt_box/alphasense_driver_node/cam3/color/image: cam3_sensor_frame_helper
/gt_box/alphasense_driver_node/cam4: cam4_sensor_frame
/gt_box/alphasense_driver_node/cam5: cam5_sensor_frame
/gt_box/hdr_front/image_raw: hdr_front
/gt_box/hdr_left/image_raw: hdr_left
/gt_box/hdr_right/image_raw: hdr_right
/gt_box/zed2i_driver_node/left_raw/image_raw_gray: zed2i_left_camera_optical_frame
/gt_box/zed2i_driver_node/right_raw/image_raw_gray: zed2i_right_camera_optical_frame