lpc:
  - /anymal_low_level_controller/actuator_readings
  - /anymal_low_level_controller/actuator_readings_extended_throttled
  - /alma_low_level_controller/actuator_readings
  - /alma_low_level_controller/actuator_readings_extended_throttled
  - /bpearl_front/packets_difop
  - /bpearl_front/packets
  - /bpearl_rear/packets_difop
  - /bpearl_rear/packets
  - /chrony_monitor_lpc/status
  - /cpu_loupe_lpc/cpu_loupe
  - /cpu_monitor_lpc/status
  - /depth_camera_front_upper/depth/camera_info
  - /depth_camera_front_upper/depth/image_rect_raw
  - /depth_camera_front_upper/infra1/image_rect_raw
  - /depth_camera_front_lower/depth/camera_info
  - /depth_camera_front_lower/depth/image_rect_raw
  - /depth_camera_front_lower/infra1/image_rect_raw
  - /depth_camera_rear_upper/depth/camera_info
  - /depth_camera_rear_upper/depth/image_rect_raw
  - /depth_camera_rear_upper/infra1/image_rect_raw
  - /depth_camera_rear_lower/depth/camera_info
  - /depth_camera_rear_lower/depth/image_rect_raw
  - /depth_camera_rear_lower/infra1/image_rect_raw
  - /debug_info
  - /disk_monitor_lpc/status
  - /distance_tracker/total_distance
  - /distance_tracker/display
  - /foot_scan
  - /inspection_payload_bt/status
  - /inspection_payload_bt/status_report
  - /inspection_payload_bt/topic_status_report
  - /inspection_payload_bt/homing_timer
  - /inspection_payload_bt/active_client
  - /inspection_payload_bt/active_client_path
  - /inspection_payload_bt/mission_time
  - /inspection_payload_bt/robot_is_moving
  - /motion_reference/command_pose
  - /motion_reference/command_twist
  - /memory_monitor_lpc/status
  - /network/receiver_stats
  - /network/sender_stats
  - /network_monitor_lpc/status
  - /path_logger/logged_path
  - /path_logger/reverse_path
  - /ping_monitor_anymal/markers
  - /pdb/battery_state
  - /pdb/intrinsic_state
  - /pdb/power_state
  - /resource_database/reports
  - /sensors/battery_voltage
  - /sensors/imu
  - /soft_emcy_stop
  - /state_estimator/alma_state
  - /state_estimator/anymal_state
  - /state_estimator/odometry
  - /state_estimator/pose_in_odom
  - /state_estimator/twist_throttle
  - /pinger_anymal_to_baserouter/ping
  - /pinger_anymal_to_dx2_alpha/ping
  - /pinger_anymal_to_dx2_beta/ping
  - /pinger_anymal_to_dx2_gamma/ping
  - /pinger_anymal_to_dx2_delta/ping
  - /pinger_anymal_to_dx2_epsilon/ping
  - /pinger_anymal_to_dx2_zeta/ping
  - /pinger_anymal_to_dx2_eta/ping
  - /pinger_anymal_to_dx2_theta/ping
  - /pinger_anymal_to_missionctrl/ping
  - /pinger_lpc_to_dx2_onboard/ping
  - /pinger_lpc_to_apc/ping
  - /pinger_lpc_to_jetson/ping
  - /pinger_lpc_to_npc/ping
  - /ping_monitor/markers
npc:
  - /alphasense_driver_ros/imu
  - /anymal/absolute_reference
  - /anymal_1/tf/base_to_map_in_map
  - /anymal_2/tf/base_to_map_in_map
  - /anymal_3/tf/base_to_map_in_map
  - /anymal_4/tf/base_to_map_in_map
  - /anymal_5/tf/base_to_map_in_map
  - /anymal_6/tf/base_to_map_in_map
  - /art_planner/path
  - /art_planner/rsl_plan_path/cancel
  - /art_planner/rsl_plan_path/goal
  - /audio/audio_raw
  - /behavior_engine/status
  - /chrony_monitor_npc/status
  - /clicked_point
  - /colorless_uniform_mapper/local_point_cloud
  - /compslam_lio/full_path
  - /compslam_lio/odometry
  - /compslam_lio/map
  - /compslam_lio/map_optimized
  - /cpu_monitor_npc/status
  - /cpu_loupe_npc/cpu_loupe
  - /depth_camera_front/depth/camera_info
  - /depth_camera_front/depth/image_rect_raw
  - /depth_camera_front/infra1/image_rect_raw
  - /depth_camera_left/depth/camera_info
  - /depth_camera_left/depth/image_rect_raw
  - /depth_camera_left/infra1/image_rect_raw
  - /depth_camera_rear/depth/camera_info
  - /depth_camera_rear/depth/image_rect_raw
  - /depth_camera_rear/infra1/image_rect_raw
  - /depth_camera_right/depth/camera_info
  - /depth_camera_right/depth/image_rect_raw
  - /depth_camera_right/infra1/image_rect_raw
  - /dinolite_microscope/image_raw/requested/compressed
  - /disk_monitor_npc/status
  - /footcontact_history/RF_FOOT
  - /inspection_payload/command
  - /inspection_payload/joint_states
  - /inspection_payload/joint_states_zoh
  - /inspection_payload/state
  - /inspection_payload_rsl/zoom_image_time_stamps
  - /integrated_to_init_CORRECTED
  - /lidar/packets
  - /local_guidance_path_follower/controller_reference_marker
  - /local_guidance_path_manager/received_global_path
  - /memory_monitor_npc/status
  - /msf_compslam_lio_body_imu/msf_core/odometry
  - /network_monitor_npc/status
  - /pinger_npc_to_apc/ping
  - /pinger_npc_to_jetson/ping
  - /pinger_npc_to_lpc/ping
  - /point_cloud_filter/lidar/point_cloud_filtered
  - /resource_database/reports
  - /thermal_camera/detection_image
  - /thermal_camera/color/camera/camera_info
  - /thermal_camera/color/large/scale/scanned/image_raw
  - /thermal_camera/raw/scanned/thermal_image
  - /transform_aft_mapped_to_init_CORRECTED
  - /wide_angle_camera_front/image_color_rect/compressed
  - /wide_angle_camera_front/camera_info
  - /wide_angle_camera_rear/image_color_rect/compressed
  - /wide_angle_camera_rear/camera_info
  - /zoom_camera/camera_info
  - /zoom_camera/focal_length
jetson:
  - /alphasense_driver_ros/cam3/debayered/slow/compressed
  - /alphasense_driver_ros/cam4/debayered/slow/compressed
  - /alphasense_driver_ros/cam5/debayered/slow/compressed
  - /alphasense_driver_ros/cam3/camera_info
  - /alphasense_driver_ros/cam4/camera_info
  - /alphasense_driver_ros/cam5/camera_info
  - /chrony_monitor_jetson/status
  - /cpu_loupe_jetson/cpu_loupe
  - /disk_monitor_jetson/status
  - /elevation_mapping/elevation_map_recordable
  - /elevation_mapping/statistics
  - /gpu_monitor_jetson
  - /memory_monitor_jetson/status
  - /network_monitor_jetson/status
  - /safety_checker/traversabiliy_safety_status
  - /safety_checker/footprint_polygon
  - /safety_checker/untraversable_polygon
  - /pinger_jetson_to_lpc/ping
  - /pinger_jetson_to_npc/ping
  - /pinger_jetson_to_apc/ping
orin:
  - /hdr_camera
apc:
  - /chrony_monitor_apc/status
  - /cpu_loupe_apc/cpu_loupe
  - /disk_monitor_apc/status
  - /gpu_monitor_apc
  - /memory_monitor_apc/status
  - /network_monitor_apc/status
  - /pinger_apc_to_lpc/ping
  - /pinger_apc_to_npc/ping
  - /pinger_apc_to_jetson/ping
