metadata:
  camera_intrinsics:
    - alias: zed2i_depth_caminfo
      file: "{}_jetson_zed2i_depth.bag"
      topic: /gt_box/zed2i/zed_node/depth/camera_info

    - alias: zed2i_left_caminfo
      file: "{}_jetson_zed2i_images.bag"
      topic: "/gt_box/zed2i/zed_node/left/camera_info"
    - alias: zed2i_right_caminfo
      file: "{}_jetson_zed2i_images.bag"
      topic: "/gt_box/zed2i/zed_node/right/camera_info"

    - alias: alphasense_cam1_caminfo
      file: "{}_nuc_alphasense.bag"
      topic: "/gt_box/alphasense_driver_node/cam1/color/camera_info"
    - alias: alphasense_cam2_caminfo
      file: "{}_nuc_alphasense.bag"
      topic: "/gt_box/alphasense_driver_node/cam2/color/camera_info"
    - alias: alphasense_cam3_caminfo
      file: "{}_nuc_alphasense.bag"
      topic: "/gt_box/alphasense_driver_node/cam3/color/camera_info"
    - alias: alphasense_cam4_caminfo
      file: "{}_nuc_alphasense.bag"
      topic: "/gt_box/alphasense_driver_node/cam4/color/camera_info"
    - alias: alphasense_cam5_caminfo
      file: "{}_nuc_alphasense.bag"
      topic: "/gt_box/alphasense_driver_node/cam5/color/camera_info"

    - alias: hdr_left_caminfo
      file: "{}_jetson_hdr_left_updated.bag"
      topic: "/gt_box/hdr_left/camera_info"
    - alias: hdr_front_caminfo
      file: "{}_jetson_hdr_front_updated.bag"
      topic: "/gt_box/hdr_front/camera_info"
    - alias: hdr_right_caminfo
      file: "{}_jetson_hdr_right_updated.bag"
      topic: "/gt_box/hdr_right/camera_info"

    - alias: anymal_cam_front_lower
      file: "{}_lpc_depth_cameras.bag"
      topic: "/depth_camera_front_lower/depth/camera_info"
    - alias: anymal_cam_front_upper
      file: "{}_lpc_depth_cameras.bag"
      topic: "/depth_camera_front_upper/depth/camera_info"
    - alias: anymal_cam_rear_lower
      file: "{}_lpc_depth_cameras.bag"
      topic: "/depth_camera_rear_lower/depth/camera_info"
    - alias: anymal_cam_rear_upper
      file: "{}_lpc_depth_cameras.bag"
      topic: "/depth_camera_rear_upper/depth/camera_info"
  frame_transforms:
    base_frame: base
    file: "{}_tf_static.bag"
    topic: /tf_static

data:
  image_topics:
    - alias: zed2i_depth
      file: "{}_jetson_zed2i_depth.bag"
      topic: "/gt_box/zed2i/zed_node/depth_mono/depth_registered/compressed"
      compressed: true
      format: png
    - alias: zed2i_confidence
      file: "{}_jetson_zed2i_depth.bag"
      topic: "/gt_box/zed2i/zed_node/confidence_mono/confidence_map/compressed"
      format: png
      compressed: true

    - alias: zed2i_left
      file: "{}_jetson_zed2i_images.bag"
      topic: "/gt_box/zed2i/zed_node/left/image_rect_color/compressed"
      format: jpeg
      compressed: true
    - alias: zed2i_right
      file: "{}_jetson_zed2i_images.bag"
      topic: "/gt_box/zed2i/zed_node/right/image_rect_color/compressed"
      format: jpeg
      compressed: true

    - alias: alphasense_cam1
      file: "{}_nuc_alphasense.bag"
      topic: "/gt_box/alphasense_driver_node/cam1/color/image/compressed"
      format: jpeg
      compressed: true
    - alias: alphasense_cam2
      file: "{}_nuc_alphasense.bag"
      topic: "/gt_box/alphasense_driver_node/cam2/color/image/compressed"
      format: jpeg
      compressed: true
    - alias: alphasense_cam3
      file: "{}_nuc_alphasense.bag"
      topic: "/gt_box/alphasense_driver_node/cam3/color/image/compressed"
      format: jpeg
      compressed: true
    - alias: alphasense_cam4
      file: "{}_nuc_alphasense.bag"
      topic: "/gt_box/alphasense_driver_node/cam4/color/image/compressed"
      format: jpeg
      compressed: true
    - alias: alphasense_cam5
      file: "{}_nuc_alphasense.bag"
      topic: "/gt_box/alphasense_driver_node/cam5/color/image/compressed"
      format: jpeg
      compressed: true

    - alias: hdr_left
      file: "{}_jetson_hdr_left_updated.bag"
      topic: "/gt_box/hdr_left/image_raw/compressed"
      format: jpeg
      compressed: true
    - alias: hdr_front
      file: "{}_jetson_hdr_front_updated.bag"
      topic: "/gt_box/hdr_front/image_raw/compressed"
      format: jpeg
      compressed: true
    - alias: hdr_right
      file: "{}_jetson_hdr_right_updated.bag"
      topic: "/gt_box/hdr_right/image_raw/compressed"
      format: jpeg
      compressed: true

    - alias: anymal_cam_front_lower
      file: "{}_lpc_depth_cameras.bag"
      topic: "/depth_camera_front_lower/depth/image_rect_raw"
      format: png
      compressed: false
    - alias: anymal_cam_front_upper
      file: "{}_lpc_depth_cameras.bag"
      topic: "/depth_camera_front_upper/depth/image_rect_raw"
      format: png
      compressed: false
    - alias: anymal_cam_rear_lower
      file: "{}_lpc_depth_cameras.bag"
      topic: "/depth_camera_rear_lower/depth/image_rect_raw"
      format: png
      compressed: false
    - alias: anymal_cam_rear_upper
      file: "{}_lpc_depth_cameras.bag"
      topic: "/depth_camera_rear_upper/depth/image_rect_raw"
      format: png
      compressed: false

  lidar_topics:
    - alias: hesai
      file: "{}_nuc_hesai_post_processed.bag"
      topic: "/gt_box/hesai/points"
      max_points: 64000
      attributes:
        - intensity
        - ring
        - timestamp

    - alias: livox
      file: "{}_nuc_livox.bag"
      topic: "/gt_box/livox/lidar"
      max_points: 64000
      attributes:
        - intensity
        - tag
        - line
        - timestamp

    - alias: dlio
      file: "{}_hesai_dlio.bag"
      topic: "/dlio/deskewed_point_cloud"
      max_points: 64000
      attributes:
        - intensity
        - timestamp

  imu_topics:
    - alias: adis_imu
      file: "{}_jetson_adis.bag"
      topic: "/gt_box/adis16475_node/imu"

    - alias: ap20_imu
      file: "{}_jetson_ap20_synced.bag"
      topic: "/gt_box/ap20/imu"

    - alias: stim_imu
      file: "{}_jetson_stim.bag"
      topic: "/gt_box/stim320/imu"

    - alias: livox_imu_si_compliant
      file: "{}_nuc_livox.bag"
      topic: "/gt_box/livox/imu_si_compliant"

    - alias: zed2i_imu
      file: "{}_jetson_zed2i_prop.bag"
      topic: "/gt_box/zed2i/zed_node/imu/data"

    # do we want both?
    - alias: cpt7_imu
      file: "{}_nuc_cpt7.bag"
      topic: "/gt_box/cpt7/gps/imu"

    - alias: cpt7_imu_offline_novatel
      file: "{}_cpt7_raw_imu.bag"
      topic: "/gt_box/cpt7/offline_from_novatel_logs/imu"

    - alias: anymal_imu
      file: "{}_lpc_anymal_imu.bag"
      topic: "/sensors/imu"

    - alias: alphasense_imu
      file: "{}_nuc_alphasense.mcap"
      topic: "/gt_box/alphasense_driver_node/imu"

  # we should use better aliases that are conistent with the corresponding point clouds / poses
  odometry_topics:
    - alias: cpt7_odometry
      file: "{}_nuc_cpt7.bag"
      topic: "/gt_box/cpt7/odom"
    - alias: zed2i_odometry
      file: "{}_jetson_zed2i_prop.bag"
      topic: "/gt_box/zed2i/zed_node/odom"

  nav_sat_fix_topics:
    - alias: cpt7_gps
      file: "{}_nuc_cpt7.bag"
      topic: "/gt_box/cpt7/gps/fix"

  magnetic_field_topics:
    - alias: zed2i_magnetic_field
      file: "{}_jetson_zed2i_prop.bag"
      topic: "/gt_box/zed2i/zed_node/imu/mag"

  # is this a duplicate of the "ground_truth" stuff?
  point_topics:
    - alias: prism
      file: "{}_jetson_ap20_synced.bag"
      topic: "/gt_box/ap20/prism_position"

  singleton_transform_topics:
    - alias: zed2i_tf
      file: "{}_jetson_zed2i_tf.bag"
      topic: "/tf"

  fluid_pressure_topics:
    - alias: zed2i_pressure
      file: "{}_jeson_zed2i_prop.bag"
      topic: "/gt_box/zed2i/zed_node/barometer"

  temperature_topics:
    - alias: stim320_accelerometer_temp
      file: "{}_jetson_stim.bag"
      topic: "/gt_box/stim320/acceletometer_temperature"

    - alias: stim320_gyroscope_temp
      file: "{}_jetson_stim.bag"
      topic: "/gt_box/stim320/gyroscope_temperature"
