metadata:
  camera_intrinsics:
    - alias: depth_camera_right_caminfo
      file: "*_anymal_depth_cameras.bag"
      topic: "/anymal/depth_camera/right/depth/camera_info"

  frame_transforms:
    - frame_id: depth_camera_right
      file: "*_tf_minimal.bag"
      topic: /tf_static
      reference_frame_id: base

data:
  image_topics:
    # - alias: depth_camera_right
    #   file: "*_anymal_depth_cameras.bag"
    #   topic: "/anymal/depth_camera/right/depth/image_rect_raw"
    #   format: png
    #   compressed: false
    #   depth: true
    #   camera_intrinsics: depth_camera_right_caminfo
    #   description: "15Hz - 848x480 - IntelRealsense D435i right (Integrated in ANYbotics ANYmal D)"
    - alias: zed2i_depth_image
      file: "*_zed2i_depth.bag"
      topic: "/boxi/zed2i/depth/image_raw/compressedDepth"
      format: png
      compressed: false
      depth: true
      camera_intrinsics: depth_camera_right_caminfo
      description: "15Hz - 1920x1080 - Stereolabs Zed2i - generated Stereolabs SDK 4.2 (mounted up-side-down / we flipped the naming of the left and right camera w.r.t. ZED2i driver)"
