metadata:
  frame_transforms:

data:
  # pose_topics:
  #   - alias: zed2i_vio_map
  #     file: "*_zed2i_vio.bag"
  #     topic: "/boxi/zed2i_vio/map"
  #     covariance: True

  imu_topics:
    - alias: adis_imu
      file: "*_adis.bag"
      topic: "/boxi/adis/imu"
      description: "Analog Devices ADIS16475-2 200Hz"

    - alias: alphasense_imu
      file: "*_alphasense_imu.bag"
      topic: "/boxi/alphasense/imu"
      description: "Bosch BMI085 200Hz (Integrated in Sevensense CoreResearch/Alphasense)"

    - alias: ap20_imu
      file: "*_ap20_imu.bag"
      topic: "/boxi/ap20/imu"
      description: "Leica Geosystems AP20 200Hz (data is only available while the bluetooth conntetion to the MS60 is active)"

    - alias: stim320_imu
      file: "*_stim320_imu.bag"
      topic: "/boxi/stim320/imu"
      description: "Safran STIM320 500Hz"

    - alias: livox_imu
      file: "*_livox_imu.bag"
      topic: "/boxi/livox/imu"
      description: "TDK ICM40609 200Hz (integrated in Livox Mid360)"

    # not used according to Jonas
    # - alias: zed2i_imu
    #   file: "*_zed2i_prop.bag"
    #   topic: "/boxi/zed2i/imu"

    - alias: cpt7_imu
      file: "*_cpt7_imu.bag"
      topic: "/boxi/cpt7/imu"
      description: "Honeywell HG4930 100Hz (integrated in Novatel CPT7)"

    - alias: anymal_imu
      file: "*_anymal_imu.bag"
      topic: "/anymal/imu"
      description: "Epsoon 400HZ (integrated in ANYbotics ANYmal D)"

    # TODO: only includes /tf topic
    # - alias: cpt7_imu_acc_bias
    #   file: "*_cpt7_ie_rt.bag"
    #   topic: "/boxi/inertial_explorer/rt/cpt7_imu_acc_bias"

    # TODO: only includes /tf topic
    # - alias: cpt7_imu_gyro_drift
    #   file: "*_cpt7_ie_rt.bag"
    #   topic: "/boxi/inertial_explorer/rt/cpt7_imu_gyro_drift"

  # fluid_pressure_topics:
  #   - alias: zed2i_pressure
  #     file: "*_zed2i_prop.bag"
  #     topic: "/boxi/zed2i/baro/pressure"

  # magnetic_field_topics:
  #   - alias: zed2i_magnetic_filed
  #     file: "*_zed2i_prop.bag"
  #     topic: "/boxi/zed2i/magnetic_field"

  odometry_topics:
    - alias: dlio_map_odometry
      file: "*_dlio.bag"
      topic: "/boxi/dlio/lidar_map_odometry"
      description: "Direct LiDAR Inetrial Odometry using HG4930 and Hesai-XT32 - provides transform from dlio_map to hesai_lidar"

    # - alias: zed2i_vio_odometry
    #  file: "*_zed2i_vio.bag"
    #  topic: "/boxi/zed2i_vio/odom"

    # TODO: only includes /tf topic
    # - alias: cpt7_ie_rt_odometry
    #   file: "*_cpt7_ie_rt.bag"
    #   topic: "/boxi/inertial_explorer/rt/odometry"

    - alias: cpt7_ie_tc_odometry
      file: "*_cpt7_ie_tc.bag"
      topic: "//boxi/inertial_explorer/tc/odometry"
      description: "CPT7 Interial Explorer Tightly Coupled post processing - provides transform from world to cpt7_imu. The world frame origin is defined by the pose the recording started != gloabl GPS coordaintes"

    - alias: anymal_state_odometry
      file: "*_anymal_state.bag"
      topic: "/anymal/state_estimator/odometry"
      description: "Anymal state estimator odometry - provides transform from odom to base. The odometry frame is locally consistent. Bloesch et al. 2018, https://roboticsproceedings.org/rss08/p03.pdf"

  point_topics:
    - alias: prism_position
      file: "*_ap20_prism_position.bag"
      topic: "/boxi/ap20/prism_position"
      description: "Leica Geosystems AP20 prism position - provides transform from MS60 Totalstation frame to to prism. This reference frame is drift-free."
  singleton_transform_topics:
    - alias: dlio_tf
      file: "*_dlio.bag"
      topic: "/tf"
      description: "Direct LiDAR Inetrial Odometry using HG4930 and Hesai-XT32 - provides transform from dlio_map to hesai_lidar"
    - alias: cpt7_ie_tc_tf
      file: "*_cpt7_ie_tc.bag"
      topic: "/tf"
      description: "CPT7 Interial Explorer Tightly Coupled post processing - provides transform from world to cpt7_imu. The world frame origin is defined by the pose the recording started != gloabl GPS coordaintes"
    - alias: cpt7_ie_rt_tf
      file: "*_cpt7_ie_rt.bag"
      topic: "/tf"
      description: "CPT7 Interial Explorer Real Time post processing - provides transform from world to cpt7_imu. The world frame origin is defined by the pose the recording started != gloabl GPS coordaintes"

  # nav_sat_fix_topics:
    # TODO: only includes /tf topic
    # - alias: navsatfix_cpt7_ie_rt
    #   file: "*_cpt7_ie_rt.bag"
    #   topic: "/boxi/inertial_explorer/rt/navsatfix"

    # TODO: only includes /tf topic
    # - alias: navsatfix_origin_cpt7_ie_rt
    #   file: "*_cpt7_ie_rt.bag"
    #   topic: "/boxi/inertial_explorer/rt/navsatfix_origin"

    # - alias: navsatfix_cpt7_ie_tc
    #   file: "*_cpt7_ie_tc.bag"
    #   topic: "/boxi/inertial_explorer/tc/navsatfix"
    #   description: "CPT7 Interial Explorer Tightly Coupled post processing - Includes raw GNSS data."

    # TODO: not included in the bag file
    # - alias: navsatfix_origin_cpt7_ie_tc
    #   file: "*_cpt7_ie_tc.bag"
    #   topic: "/boxi/inertial_explorer/tc/navsatfix_origin"

  gnss_raw_topics:
    #   # TODO: only includes /tf topic
    #   # - alias: gnss_origin_cpt7_ie_rt
    #   #   file: "*_cpt7_ie_rt.bag"
    #   #   topic: "/boxi/inertial_explorer/rt/origin"

    #   # TODO: only includes /tf topic
    #   # - alias: gnss_raw_cpt7_ie_rt
    #   #   file: "*_cpt7_ie_rt.bag"
    #   #   topic: "/boxi/inertial_explorer/rt/raw"

    #   # TODO: not included in the bag file
    #   # - alias: gnss_origin_cpt7_ie_tc
    #   #   file: "*_cpt7_ie_tc.bag"
    #   #   topic: "/boxi/inertial_explorer/tc/origin"

    - alias: gnss_raw_cpt7_ie_tc
      file: "*_cpt7_ie_tc.bag"
      topic: "/boxi/inertial_explorer/tc/raw"
      description: "CPT7 Interial Explorer Tightly Coupled post processing - Includes raw GNSS data."

  anymal_state_topics:
    - alias: anymal_state_state_estimator
      file: "*_anymal_state.bag"
      topic: "/anymal/state_estimator/anymal_state"
      number_of_joints: 12
      feet: ["LF_FOOT", "RF_FOOT", "LH_FOOT", "RH_FOOT"]
      description: "Joint-level and other ANYmal state information."


  # temperature_topics:
  #   - alias: stim320_gyroscope_temperature
  #     file: "*_stim320_imu.bag"
  #     topic: "/boxi/stim320/gyroscope_temperature"

  #   - alias: stim320_acceletometer_temperature
  #     file: "*_stim320_imu.bag"
  #     topic: "/boxi/stim320/acceletometer_temperature"

  battery_state_topics:
    - alias: anymal_state_battery
      file: "*_anymal_state.bag"
      topic: "/anymal/battery_state"
      description: "Battery state of ANYmal."

  actuator_readings_topics:
    - alias: anymal_state_actuator
      file: "*_anymal_state.bag"
      topic: "/anymal/actuator_readings"
      number_of_actuators: 12
      description: "Actuator state of ANYmal."

  imu_vector_topics:
    - alias: cpt7_tc_imu_acc_bias
      file: "*_cpt7_ie_tc.bag"
      topic: "/boxi/inertial_explorer/tc/cpt7_imu_acc_bias"

    - alias: cpt7_tc_imu_gyro_drift
      file: "*_cpt7_ie_tc.bag"
      topic: "/boxi/inertial_explorer/tc/cpt7_imu_gyro_drift"

  anymal_twist_topics:
    - alias: anymal_command_twist
      file: "*_anymal_command.bag"
      topic: "/anymal/twist_command"
# TODO: Debug
# anymal_debug_topics:
#   - alias: anymal_locomotion
#     file: "*_anymal_locomotion.bag"
#     topic: "/anymal/locomotion_policy/debug_info"

#### TODO: Not yet implemented!  ###################################################

# TODO: implement topic of type any_velodyne_msgs/VelodyneScan
# only generate the topic_name and frame_id no conversion needed
#   - alias: anymal_velodyne_packets
#     file: "*_anymal_velodyne_packets.bag"
#     topic: "/anymal/velodyne/packets"

# TODO: implement topic of type grid_map_msgs/GridMap
# only generate the topic_name and frame_id no conversion needed
#     - alias: anymal_elevation
#       file: "*_anymal_elevation.bag"
#       topic: "/anymal/elevation_mapping/elevation_map_raw"

######################################################################################
